[tool.black]
line-length = 79
target-version = ['py311']
extend-exclude = '''
^/dist
^/man
^/*.egg-info
^/tmp
^/build
'''

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
pythonpath = ["retain"]

[tool.pyright]
#venvPath = "venv"
include = ["retain/*.py"]

